# Generated by Django 6.0.4 on 2026-09-04 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('games', '0001_initial'),
        ('venue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BEVERAGE', 'Drinks & Energy Beverages'), ('SNACK', 'Gaming Snacks & Meals'), ('HARDWARE', 'Pro Peripherals & VR Gear'), ('EXTRA', 'Extra Time / Coaching')], default='BEVERAGE', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('icon', models.CharField(default='coffee', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='addons/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=1, default=3.0, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('features_list', models.TextField(help_text='Line-separated list of perks (e.g. 1 Energy Drink included)')),
                ('badge_text', models.CharField(blank=True, default='POPULAR', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('included_zones', models.ManyToManyField(blank=True, related_name='packages', to='venue.zone')),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('banner_tag', models.CharField(default='SAVE BIG', max_length=50)),
                ('description', models.TextField()),
                ('offer_type', models.CharField(choices=[('PERCENT', 'Percentage Discount (%)'), ('FLAT', 'Flat Amount Discount (₹)'), ('HAPPY_HOUR', 'Happy Hour Special'), ('WEEKDAY', 'Weekday Deal'), ('WEEKEND', 'Weekend Overdrive'), ('STUDENT', 'Student Verification Discount'), ('BIRTHDAY', 'Birthday Freebie / Discount'), ('FIRST_BOOKING', 'First Time Gamer Offer'), ('GROUP', 'Group Booking Discount (3+ seats)')], default='PERCENT', max_length=30)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 20) or Flat INR (e.g. 100)', max_digits=8)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount in INR', max_digits=8, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_total_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
                ('current_uses_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_games', models.ManyToManyField(blank=True, related_name='offers', to='games.game')),
                ('applicable_zones', models.ManyToManyField(blank=True, related_name='offers', to='venue.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='pricing.offer')),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peak_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('peak_start_hour', models.PositiveIntegerField(default=18, help_text='24-hr format (e.g. 18 = 6 PM)')),
                ('peak_end_hour', models.PositiveIntegerField(default=23, help_text='24-hr format (e.g. 23 = 11 PM)')),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='venue.zone')),
            ],
        ),
    ]
