# Generated by Django 6.0.4 on 2026-09-04 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='gamepad-2', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='games/covers/')),
                ('cover_url', models.URLField(blank=True, help_text='Fallback external image URL', max_length=500)),
                ('player_mode', models.CharField(choices=[('SINGLE', 'Single Player'), ('COOP', 'Co-op 2-4 Players'), ('MULTIPLAYER', 'Massive Multiplayer / Esports')], default='MULTIPLAYER', max_length=30)),
                ('max_players', models.PositiveIntegerField(default=1)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('release_year', models.PositiveIntegerField(default=2024)),
                ('developer', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True, help_text='False if game is undergoing update/patch')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_release', models.BooleanField(default=False)),
                ('system_requirements', models.TextField(blank=True, default='Optimized for 240FPS Ultra on Gammers Adda RTX 4090 rigs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platforms', models.ManyToManyField(blank=True, related_name='games', to='venue.platform')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.genre')),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GameScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/screenshots/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.game')),
            ],
        ),
    ]
