[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"

[deploy]
startCommand = "gunicorn gammers_adda.wsgi"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
