# Generated by Django 6.0.4 on 2026-09-04 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform_type', models.CharField(choices=[('PC', 'PC Gaming Rig'), ('PS5', 'PlayStation 5 Pro'), ('XBOX', 'Xbox Series X'), ('VR', 'VR Pod (Quest 3 / PSVR2)'), ('SIM_RACING', 'Sim Racing Cockpit')], default='PC', max_length=30)),
                ('specs', models.TextField(help_text='GPU, CPU, RAM, Display, Peripherals specs')),
                ('icon', models.CharField(default='cpu', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
                ('icon', models.CharField(default='monitor', max_length=50)),
                ('theme_color', models.CharField(default='#FF3B4D', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='zones/')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. PC-01, PS5-02, SIM-01', max_length=20, unique=True)),
                ('grid_row', models.PositiveIntegerField(default=1)),
                ('grid_col', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Temporary Hold'), ('OCCUPIED', 'Occupied / In Session'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('maintenance_reason', models.CharField(blank=True, max_length=255)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venue.platform')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venue.zone')),
            ],
            options={
                'ordering': ['zone', 'grid_row', 'grid_col', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SeatMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='venue.seat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='platform',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='venue.zone'),
        ),
    ]
