# Generated by Django 6.0.4 on 2026-09-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / In Creation'), ('SEAT_HELD', 'Seat Held (Pending Payment)'), ('PAYMENT_PENDING', 'Payment Processing'), ('CONFIRMED', 'Confirmed & Booked'), ('CHECKED_IN', 'Checked In at Venue'), ('IN_SESSION', 'Active In Session'), ('COMPLETED', 'Completed Session'), ('EXPIRED', 'Seat Hold Expired'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled by Customer'), ('REFUND_PENDING', 'Refund Processing'), ('REFUNDED', 'Refund Completed'), ('NO_SHOW', 'No Show')], default='DRAFT', max_length=30)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('addons_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coupon_code_used', models.CharField(blank=True, max_length=50, null=True)),
                ('is_walkin', models.BooleanField(default=False)),
                ('qr_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-booking_date', '-start_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled / Waiting Check-in'), ('IN_PROGRESS', 'Active In Progress'), ('EXTENDED', 'Session Extended'), ('COMPLETED', 'Session Completed'), ('TERMINATED', 'Manually Ended by Staff')], default='SCHEDULED', max_length=20)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('expected_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('extended_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('held_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
