# Generated by Django 6.0.4 on 2026-09-04 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('pricing', '0001_initial'),
        ('venue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.offer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='pricing.gamingpackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='venue.zone'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.addon'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='venue.seat'),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='venue.seat'),
        ),
        migrations.AddField(
            model_name='seathold',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_holds', to='venue.seat'),
        ),
        migrations.AddField(
            model_name='seathold',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookingseat',
            unique_together={('booking', 'seat')},
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['booking_date', 'start_time', 'end_time'], name='bookings_se_booking_76bbac_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['held_until'], name='bookings_se_held_un_d06336_idx'),
        ),
    ]
